# Generated by Django 4.0.4 on 2025-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('upass', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
