# Generated by Django 4.0.4 on 2025-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('pdtname', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
